# Generated by Django 2.2 on 2021-08-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('semi_restful_tv_shows_app', '0002_auto_20210805_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='release_date',
            field=models.DateField(),
        ),
    ]
